name: multi_repo_tester
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  process_run: ^0.12.1
  actors: ^0.7.0
  args: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
